### ISSUE TITLE
How many gaussians in the basis set?

### ISSUE THREAD

**Issue by maxlevesque** [haranjackson/GaussianDeconvolution#1]
Hey,
First of all thanks for making your repo public. Gaussian deconvolution is something I wanted to play with for years, litteraly. Sadly, I don't know python, even if your source is very readable (double thanks). I don't understand something: Can I control the number of gaussians in the basis set ?

**Comment by haranjackson** [comment]
Hi Max, thanks for your interest. The code here just performs the inverse of a Gaussian convolution operation on whatever input data you give it. If this data is composed of a superposition of Gaussian curves, each curve will have its variance decreased and its height increased by amounts deducible from equations (1) and (2) in the ReadMe. The curves are then more easy to distinguish from one another.

This is a small part of a larger code I wrote for automatically detecting superimposed Gaussian curves. That code performs this deconvolution operation, then attempts to detect Gaussian peaks, then fits an estimated number of Gaussian curves to the data. You can specify or set limits on the number of curves it should attempt to fit. If this is something you'd be interested in seeing then we can discuss it more!

**Comment by maxlevesque** [comment]
Hi Haran, thanks for your answer, and sorry for misunderstanding. What I aim to is to fit some radial functions by gaussians functions. For instance, even if it sounds weird, one major quantum chemistry package (BigDFT) replaces the simple inverse function by a sum of ~80 gaussians. This trick has tremendous impact on their performance. Any idea would be welcome.

**Comment by haranjackson** [comment]
Hi Max, that sounds a bit different to the kind of problems I was working on previously, although maybe I can be of some help. I'll drop you an email and we can discuss it further.
